version: "3.5"

services:
  app:
    image: node:16.14.0-alpine
    container_name: task-manager
    working_dir: /app
    volumes:
      - .:/app:delegated
    environment: 
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: task_manager
      POSTGRES_PASSWORD: task_manager
      POSTGRES_DATABASE: task_manager
    ports:
      - "3001:80"
    entrypoint: [ "/app/docker/entrypoint" ]
    command: npm run start:dev
    restart: on-failure

  postgres:
    image: postgres:12.7-alpine
    container_name: task-manager-postgres
    volumes:
      - ./docker/postgres-init.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      POSTGRES_USER: task_manager
      POSTGRES_PASSWORD: task_manager
      POSTGRES_DB: task_manager
    ports:
      - "3002:5432"

networks:
  default:
    name: task_manager

